=== frankfx/CPACS_Builder/ShapeXI/src/main/resources/ShapeSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="shape">
    <xs:complexType>
      <xs:sequence>
		<xs:element name="header"> 
		  <xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="description" type="xs:string"/>
				<xs:element name="creator" type="xs:string"/>
				<xs:element name="timestamp" type="xs:string"/>
				<xs:element name="version" type="xs:string"/>
				<xs:element name="shapeVersion" type="xs:string"/>
			</xs:sequence>
		  </xs:complexType>
		</xs:element>
		<xs:element name="cube"> 
		  <xs:complexType>
			<xs:sequence>
			  <xs:element name="profiles">
				  <xs:complexType>
					<xs:sequence>
					  <xs:element name="cubeProfile" minOccurs ="1" maxOccurs ="unbounded">
						  <xs:complexType>
							<xs:sequence>
							  <xs:element name="name" type="xs:string"/>
							  <xs:element name="description" type="xs:string"/>
							  <xs:element name="pointList">
								  <xs:complexType>
									<xs:sequence>
									  <xs:element name="x" type="xs:string"/>
									  <xs:element name="y" type="xs:string"/>
									  <xs:element name="z" type="xs:string"/>
									</xs:sequence>
								  </xs:complexType>								  
							  </xs:element>
							  <xs:element name="colorList" minOccurs="0">
								  <xs:complexType>
									<xs:sequence>
									  <xs:element name="color" type="xs:string"/>
									</xs:sequence>
								  </xs:complexType>								  
							  </xs:element>							  
							</xs:sequence>
							<xs:attribute  name="id" type="xs:string" use="required"/>
						  </xs:complexType>		
					  </xs:element>
					</xs:sequence>
				  </xs:complexType>
				  <xs:unique name="UniqueCubeProfile">
					<xs:selector xpath="cubeProfile"/> 
					<xs:field xpath="@id"/> 
				  </xs:unique>
			  </xs:element>
			</xs:sequence>
		  </xs:complexType>
		</xs:element>	  
	  </xs:sequence>
	</xs:complexType>
  </xs:element>
</xs:schema>

=== frankfx/CPACS_Builder/ShapeXI/src/main/resources/Shape.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<shape xmlns="http://meinnamespace.meinefirmarrr.de"
          xsi:schemaLocation="http://meinnamespace.meinefirmarrr.de ShapeSchema.xsd">
  <header>
    <name>cube test</name>
    <description>Simple Cube test</description>
    <creator>Rene Frank</creator>
    <timestamp>2016-03-04</timestamp>
    <version>0.0</version>
    <shapeVersion>2.0</shapeVersion>
  </header>
  <cube>	
	<profiles>
       <cubeProfile id="uid_1">
         <name>Cube 1</name>
         <description>Profile build up from set of Points on Circle where may Dimensions are 1..-1</description>
         <pointList>
           <x>0.0;0.0;0.0;0.0;0.0</x>
           <y>0.0;1.0;0.0;-1.0;0.0</y>
           <z>1.0;0.0;-1.0;0.0;1.0</z>
         </pointList>
       </cubeProfile>
    </profiles>
  </cube>  
</shape>
